config/routes.rb
AcmeHireCarSystem::Application.routes.draw do

  resources :hirings
  resources :cars
  resources :users
  resources :sessions, :only => [:create, :destroy]

  match '/', :to => 'applications#home'
  match '/about',   :to => 'pages#about'
  match '/browseCar', :to => 'cars#index'
  match '/help',    :to => 'pages#help'
  match '/home', :to => 'applications#home'
  match '/newCar', :to => 'cars#new'
  match '/signin',  :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  match '/signup',  :to => 'users#new'
  match '/bookCar', :to => 'hirings#new'
  match '/user_hirings', :to =>"users#listHirings"
  match '/hirings', :to => "hirings#index"
  match '/close_hiring', :to => "hirings#close"
  root :to => 'pages#home'

 
=begin
  get "applications/home"
  get "applications/connect"
  get "applications/browseCar"
  get "applications/disconnect"
  get "applications/bookCar"
=end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
require 'digest'

class User < ActiveRecord::Base

	has_many :hirings

	attr_accessor :password
  	attr_accessible :name, :email, :password, :password_confirmation

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  	validates :name, :presence => true,
  					 :length   => { :within => 6..30 }

	validates :email, :presence => true,
					  :format   => { :with => email_regex },
					  :uniqueness => {:case_sensitive => false}

	validates :password, :presence     => true,
						 :confirmation => true,
						 :length       => { :within => 6..20 }

  	before_save :encrypt_password

	def User.authenticate(email, submitted_password)
	    user = User.find_by_email(email)

	    return nil  if user.nil?
	    return user if user.has_password?(submitted_password)
  	end		

  	def self.authenticate_with_salt(id, cookie_salt)
  		logger.debug "Authenticate with salt #{id}"
	    user = find_by_id(id)
	    (user && user.salt == cookie_salt) ? user : nil
  	end				 

	def has_password?(password_soumis)
		encrypted_password == encrypt(password_soumis)
	end

	private

	 	def encrypt_password
	      self.salt = make_salt if new_record?
	      self.encrypted_password = encrypt(password)
	    end

	    def encrypt(string)
	      secure_hash("#{salt}--#{string}")
	    end

	    def make_salt
	      secure_hash("#{Time.now.utc}--#{password}")
	    end

	    def secure_hash(string)
	      Digest::SHA2.hexdigest(string)
	    end

	    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @title = "Subscribe"
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: ' Welcome on ACME - Hire Car System.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def listHirings
    @hirings = current_user.hirings
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hirings }
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Full Name"%><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "E-mail Addresse" %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label "Password" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label "Password Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Subscribe" , :class => "btn btn-inverse" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/users/listHirings.html.erb
<h1>Listing hirings for <%= current_user.name%></h1>

<table class="table table-hover">
  <tr>
    <th>Hire date</th>
    <th>Nb days</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hirings.each do |hiring| %>
  <tr>
    <td><%= hiring.hire_date %></td>
    <td><%= hiring.nb_days %></td>
    <td><%= link_to 'Show', hiring %></td>
    <td><%= link_to 'Edit', edit_hiring_path(hiring) %></td>
    <td><%= link_to 'Destroy', hiring, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<div class="row">
   	<div class="span6 offset3">
		<h1>Subscription</h1>
		<%= render 'form' %>
		<%= link_to 'Back to Home', home_path, :class =>"btn btn-primary" , :style => "color:white;" %>
   	</div>
</div>

app/views/users/show.html.erb
<% if notice %>
	<div class="alert alert-success">
	  <button type="button" class="close" data-dismiss="alert">&times;</button>
	  <strong>Success!</strong><%= notice %>
	</div>
<% end %>
<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= link_to 'Back To Home', home_path %>