config/routes.rb
AcmeHireCarSystem::Application.routes.draw do

  resources :hirings
  resources :cars
  resources :users
  resources :sessions, :only => [:create, :destroy]

  match '/', :to => 'applications#home'
  match '/about',   :to => 'pages#about'
  match '/browseCar', :to => 'cars#index'
  match '/help',    :to => 'pages#help'
  match '/home', :to => 'applications#home'
  match '/newCar', :to => 'cars#new'
  match '/signin',  :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  match '/signup',  :to => 'users#new'
  match '/bookCar', :to => 'hirings#new'
  match '/user_hirings', :to =>"users#listHirings"
  match '/hirings', :to => "hirings#index"
  match '/close_hiring', :to => "hirings#close"
  root :to => 'pages#home'

 
=begin
  get "applications/home"
  get "applications/connect"
  get "applications/browseCar"
  get "applications/disconnect"
  get "applications/bookCar"
=end

end

app/models/hiring.rb
# == Schema Information
#
# Table name: hirings
#
#  id          :integer          not null, primary key
#  hire_date   :date
#  nb_days     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  car_id      :integer
#  customer_id :integer
#

class Hiring < ActiveRecord::Base
	belongs_to :car
	belongs_to :user
  	attr_accessible :hire_date, :nb_days, :car_id, :user_id

  	validates :car_id, :presence => true, :if => :is_car_available

  	def price
		car =  Car.find(self.car_id)
		amount = car.daily_price * self.nb_days
		
		return amount
	end

	def extra_fees
		extras_fees = 0
		if DateTime.now > self.return_date
			logger.debug "#{DateTime.now - self.return_date}"
			extra_days = (DateTime.now - self.return_date).to_i
			extras_fees= 2 * (extra_days * car.daily_price) 
		end
		return extras_fees
	end

	def return_date
		return self.hire_date + self.nb_days.days
	end

	def customer_name
		customer = User.find(self.user_id)
		return customer.name
	end

	def car_label
		car = Car.find(self.car_id)
		return car.label
	end

	def is_car_available
		car =  Car.find(self.car_id)
		hiringsWithCar = car.hirings

		range = self.hire_date..self.return_date
		ret=true
		if !hiringsWithCar.nil?
			
			hiringsWithCar.each{|hiring|
				if(range.cover?(hiring.hire_date) || range.cover?(hiring.return_date))
					ret=false
					break
				end
			}
		end
		return ret
	end
end

app/controllers/hirings_controller.rb
class HiringsController < ApplicationController
  # GET /hirings
  # GET /hirings.json
  def index
    @hirings = Hiring.all

    logger.debug "#{@hirings}"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hirings }
    end
  end

  # GET /hirings/1
  # GET /hirings/1.json
  def show
    @hiring = Hiring.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hiring }
    end
  end

  # GET /hirings/new
  # GET /hirings/new.json
  def new
    @hiring = Hiring.new params[:id]
    @cars = Car.find(:all)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hiring }
    end
  end

  # GET /hirings/1/edit
  def edit
    @hiring = Hiring.find(params[:id])
    @cars = Car.find(:all)
  end

  # POST /hirings
  # POST /hirings.json
  def create
    @hiring  = current_user.hirings.build(params[:hiring])
    @cars = Car.find(:all)

    if @hiring.is_car_available
      respond_to do |format|
        if @hiring.save
          format.html { redirect_to @hiring, notice: 'You have successfully hire a car.' }
          format.json { render json: @hiring, status: :created, location: @hiring }
        else
          format.html { render action: "new" }
          format.json { render json: @hiring.errors, status: :unprocessable_entity }
        end
      end
    else       
      flash.now[:error] = " Car isn't available for the specified date! Please chose another!"
      render 'new'
    end
  end

  # PUT /hirings/1
  # PUT /hirings/1.json
  def update
    @hiring = Hiring.find(params[:id])

    respond_to do |format|
      if @hiring.update_attributes(params[:hiring])
        format.html { redirect_to @hiring, notice: 'Hiring was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hiring.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hirings/1
  # DELETE /hirings/1.json
  def destroy
    @hiring = Hiring.find(params[:id])
    @hiring.destroy

    respond_to do |format|
      format.html { redirect_to hirings_url }
      format.json { head :no_content }
    end
  end

  def close
    @hiring = Hiring.find(params[:hiring_id])
    @hiring.open = false
    respond_to do |format| 
      if @hiring.save
        format.html { redirect_to hirings_url, notice: 'Hire Close.' }
        format.json { render json: @hiring, status: :updated, location: @hiring }
      else
        flash.now[:error] = "Ooops! An error occured, please retried!"
        format.html { redirect_to hirings_url }
      end
    end
  end
end

app/helpers/hirings_helper.rb
module HiringsHelper
end

app/views/hirings/_form.html.erb
<%= form_for(@hiring) do |f| %>
  <% if @hiring.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hiring.errors.count, "error") %> prohibited this hiring from being saved:</h2>

      <ul>
      <% @hiring.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hire_date %><br />
    <%= f.date_select :hire_date %>
  </div>
  <div class="field">
    <%= f.label :nb_days %><br />
    <%= f.text_field :nb_days %>
  </div>
  <div>
    <b>Car:</b><br>
    <select name="hiring[car_id]">
    <% @cars.each do |car| %>
           <option value="<%= car.id %>" 
            <%= ' selected' if car.id == @hiring.car_id %>>
            <%= car.label %>
           </option>
    <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hirings/edit.html.erb
<h1>Editing hiring</h1>

<%= render 'form' %>

<%= link_to 'Show', @hiring %> |
<%= link_to 'Back', hirings_path %>

app/views/hirings/index.html.erb
<h1>Listing hirings</h1>

<table class="table table-hover">
  <tr>
    <th>Customer</th>
    <th>Hire date</th>
    <th>Return date</th>
    <th>Nb days</th>
    <th>Car</th>
    <th>Amount</th>
    <th>Extra fees</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @hirings.each do |hiring| %>
  <%if !hiring.open %>
    <tr class="success">
  <% elsif hiring.extra_fees > 0 %>
    <tr class="error">
  <%else%>
    <tr>
  <%end%>
    <td><%= hiring.customer_name %></td>  
    <td><%= hiring.hire_date %></td>
    <td><%= hiring.return_date %></td>
    <td><%= hiring.nb_days %></td>
    <td><%= hiring.car_label %></td>  
    <td>£<%= hiring.price %></td>
    <td>£<%= hiring.extra_fees %></td>
    <% if hiring.open? %>
      <td>Open</td>
    <%else%>
      <td>Close</td>
    <%end%>
    <td><%= link_to 'Show', hiring %></td>
    <td><%= link_to 'Edit', edit_hiring_path(hiring) %></td>
    <td><%= link_to 'Cancel', hiring, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Close', :controller => "hirings", 
                             :action => "close", 
                             :hiring_id => hiring.id %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Hiring', new_hiring_path %>

app/views/hirings/new.html.erb
<h1>New hiring</h1>
	<% if flash[:error] %>
		<div class="alert alert-error">
		  <button type="button" class="close" data-dismiss="alert">&times;</button>
		  <strong>Error!</strong><%= flash[:error] %>
		</div>
	<% end %>
<%= render 'form' %>

<%= link_to 'Back', hirings_path %>

app/views/hirings/show.html.erb
	<% if notice %>
		<div class="alert alert-success">
		  <button type="button" class="close" data-dismiss="alert">&times;</button>
		  <strong>Success!</strong><%= notice %>
		</div>
	<% end %>
<p>
  <b>Hire date:</b>
  <%= @hiring.hire_date %>
</p>

<p>
  <b>Nb days:</b>
  <%= @hiring.nb_days %>
</p>
<p>
	<b>Voiture: </b>
	<%= @hiring.car.label %>
	<br>
	<%= image_tag @hiring.car.pic.url(:medium) %>
</p>

<%= link_to 'Edit', edit_hiring_path(@hiring) %> |
<%= link_to 'Back', hirings_path %>