config/routes.rb
AcmeHireCarSystem::Application.routes.draw do

  resources :hirings
  resources :cars
  resources :users
  resources :sessions, :only => [:create, :destroy]

  match '/', :to => 'applications#home'
  match '/about',   :to => 'pages#about'
  match '/browseCar', :to => 'cars#index'
  match '/help',    :to => 'pages#help'
  match '/home', :to => 'applications#home'
  match '/newCar', :to => 'cars#new'
  match '/signin',  :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  match '/signup',  :to => 'users#new'
  match '/bookCar', :to => 'hirings#new'
  match '/user_hirings', :to =>"users#listHirings"
  match '/hirings', :to => "hirings#index"
  match '/close_hiring', :to => "hirings#close"
  root :to => 'pages#home'

 
=begin
  get "applications/home"
  get "applications/connect"
  get "applications/browseCar"
  get "applications/disconnect"
  get "applications/bookCar"
=end

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id          :integer          not null, primary key
#  label       :string(255)
#  daily_price :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Car < ActiveRecord::Base
 	has_many :hirings
   	attr_accessible :daily_price, :label, :pic
	has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
    @title = "Our Cars"
   /# respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end/
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  def show_image
    @car = User.find(params[:id])
    send_data @car.image, :type => 'image/png',:disposition => 'inline'
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for @car,:html => { :multipart => true } do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :daily_price %><br />
    <%= f.text_field :daily_price %>
  </div>

  <div class="field">
    <%= f.label "Picture" %><br />
    <%= f.file_field :pic %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table class="table table-hover">
  <tr>
    <th></th>
    <th>Model</th>
    <th>Price (£/day)</th>
    <th></th>
    <% if !current_user.nil? && current_user.admin? %>
      <th></th>
      <th></th>
    <%end%> 
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td style="width:100px;"><%= image_tag car.pic.url(:thumb) %></td>
    <td><%= car.label %></td>
    <td>£<%= car.daily_price %></td>
    <td><%= link_to 'Show', car, :style => "color: whitel;", :class => "btn btn-info" %></td>
    <% if !current_user.nil? && current_user.admin? %>
      <td><%= link_to 'Edit', edit_car_path(car) %></td>
      <td><%= link_to 'Destroy', car, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    <%end%> 
  </tr>
<% end %>
</table>

<br />

<% if !current_user.nil? && current_user.admin? %>
  <%= link_to 'New Car', newCar_path, :class => 'btn btn-inverse'%>
<%end%>

app/views/cars/new.html.erb
<h1>New car super car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<div class="row">
	<% if notice %>
		<div class="alert alert-success">
		  <button type="button" class="close" data-dismiss="alert">&times;</button>
		  <strong>Success!</strong><%= notice %>
		</div>
	<% end %>

	<p>
	  <b>Label:</b>
	  <%= @car.label %>
	</p>

	<p>
	  <b>Daily price:</b>
	  <%= @car.daily_price %>
	</p>
	
	<%= image_tag @car.pic.url(:medium) %>

	<% if !current_user.nil? && current_user.admin? %>
		<%= link_to 'Edit', edit_car_path(@car) %>
	<%end%>
	<br>
	<%= link_to 'Back', cars_path, :class => "btn btn-inverse" %>