config/routes.rb
AcmeHireCarSystem::Application.routes.draw do

  resources :hirings
  resources :cars
  resources :users
  resources :sessions, :only => [:create, :destroy]

  match '/', :to => 'applications#home'
  match '/about',   :to => 'pages#about'
  match '/browseCar', :to => 'cars#index'
  match '/help',    :to => 'pages#help'
  match '/home', :to => 'applications#home'
  match '/newCar', :to => 'cars#new'
  match '/signin',  :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy'
  match '/signup',  :to => 'users#new'
  match '/bookCar', :to => 'hirings#new'
  match '/user_hirings', :to =>"users#listHirings"
  match '/hirings', :to => "hirings#index"
  match '/close_hiring', :to => "hirings#close"
  root :to => 'pages#home'

 
=begin
  get "applications/home"
  get "applications/connect"
  get "applications/browseCar"
  get "applications/disconnect"
  get "applications/bookCar"
=end

end

app/views/layouts/_footer.html.erb
<div class=" navbar navbar-inverse  navbar-fixed-bottom footer">
	<div class="navbar-inner">
		<div class="container">
			<div class="row-fluid">
				<div class="span6">
					<h3> About ACME</h3>
					<ul class="nav">
						<li> <a href="/contacts">Contact US</a> </li>
						<li> <a href="/faqs">FAQ</a> </li>
						<li> <a href="/conditions">Legal</a> </li>
					</ul>
				</div>

				<div class="span6">
					<h3> My Account </h3>
					<ul class="nav">
						<% if signed_in? %>
							<li> <%= link_to "My details", current_user, :id => "details"%> </li>
							<li> <%= link_to "My History", user_hirings_path, :id => "userHistory"%> </li>
							<li> <%= link_to "Delete my Account", '#', :id => "userDelete"%> </li>
						<% else %>
							<li> <%= link_to "My details", "#", :id => "details"%> </li>
							<li> <%= link_to "My History", '#', :id => "userHistory"%> </li>
							<li> <%= link_to "Delete my Account", '#', :id => "userDelete"%> </li>
						<%end%>	
					</ul>
				</div>
			</div>

			<div class="info" style="margin-left: auto;">
				<p> Copyright © bertinm Aston University - 2013 </p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
        <div class="container">
          	<%= link_to "ACME", home_path ,:class => "brand" %>
          	<div class="nav-collapse collapse">
            	<ul class="nav">
            	  	<li class="divider-vertical"></li>
	              	<li>
	              		<%= link_to "Home", home_path %>
	              	</li>
	              	<li>
	              		<%= link_to "Browse Car", browseCar_path %>
	              	</li>
	              	<% if signed_in? %>
		              	<li>
		              		<%= link_to "Book a Car", bookCar_path %>
		              	</li>
		            <%end%>
		            <% if !current_user.nil? && current_user.admin? %>
		            	<li>
		              		<%= link_to "Hiring List", hirings_path %>
		              	</li>
		            <%end%>
            	</ul>
            	<ul class="nav pull-right">
					<li class="divider-vertical"></li>

					<li>
						<% if signed_in? %>
							<%= link_to current_user.name, current_user %>
						<% else %>
							<%= link_to "Subscribe", signup_path, :id => "signup" %>
						<%end%>	
					</li>
					<li class="divider-vertical"></li>
					<li>
						<% if signed_in? %>
							<%= link_to "Logout", signout_path, :method => :delete %>
						<% else %>
							<% logger.debug "user to connect" %>
							<%= link_to "Login", '#', :id => "login"%>
						<%end%>						
					</li>
					<li class="divider-vertical"></li>
				</ul>
         	</div>
    	</div>
  	</div>
</div>

app/views/layouts/_import.html.erb
  <%= stylesheet_link_tag  "application", :media => "all" %>
  <%= stylesheet_link_tag  "bootstrap" %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap" %>
  <%= javascript_include_tag "main" %>
  <%= javascript_include_tag "jqFancyTransitions.1.8" %>

  <%= csrf_meta_tags %>

app/views/layouts/_login_modal.html.erb
<div id="loginModal" class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>ACME Car Hire System - Login</h3>
  </div>
  <div class="modal-body">
      <!-- Ruby form -->
      <%= form_for(:session, :url => signin_path, :html => { :id => "loginForm" }, :remote => true) do |f| %>
          <div class="field">
            <%= f.label "E-mail Addresse" %><br />
            <%= f.text_field :email %>
          </div>

          <div class="field">
            <%= f.label "Password" %><br />
            <%= f.password_field :password %>
          </div>
      <% end %>
      <div id="loginMessage" class="alert alert-error hide" ></div>
  </div>
  <div class="modal-footer">
    <button id="loginButton" class="btn btn-primary" type="button">Login</button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= render 'layouts/import' %>
</head>
<body style="height:auto;">
  <%= render 'layouts/header' %>
  <%= render 'layouts/login_modal' %>
  <div id="messageSuccess" class="alert alert-success hide" ></div>
  <div id="messageError" class="alert alert-error hide" ></div>
  <div class="paddingNavbar container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>